/*
 * File: app/view/GbMapContent.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gb41.view.GbMapContent', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.gbmapcontent',
	requires: [
		'Gb41.view.GbTocPanel',
		'Gb41.view.GbLegendPanel'
//		'Gb41.view.GbTocGrid'
	],
	layout: {
		type: 'accordion'
	},
	title: 'Karteninhalt',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'gbtocpanel',
					itemId: 'MyGbTocPanel',
					collapsed: true
				},
				{
					xtype: 'gblegendpanel',
					itemId: 'MyGbLegendPanel',
					id: 'legend'
				}
/*				{
					xtype: 'gbtocgrid',
					itemId: 'MyGbTocGrid',
					collapsed: false
				}
*/			]
		});

		me.callParent(arguments);
	}

});