/** This file is automatically generated by create_language_js.py */

// some data used in the examples
Ext.namespace('Ext.gb41');

Ext.gb41.languages = [
	['de', 'German', 'utf-8'],
	['en', 'English', 'ascii'],
	['es', 'Spanish/Latin American', 'utf-8'],
	['fr', 'France (France)', 'utf-8'],
	['it', 'Italian', 'ascii']
];
