/*
 * File: app/view/FormAwelLhForstfeuerZH.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gb41.view.edit.FormAwelLhForstfeuerZH', {
    extend: 'Ext.form.Panel',
    alias: 'widget.editFormAwelLhForstfeuerZH',

    layout: {
        type: 'auto'
    },
    bodyPadding: 10,
    title: 'AwelLhForstfeuerZH',

    initComponent: function () {
        var me = this;

        Ext.applyIf(me, {
            autoScroll: true,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnAdd',
                            enableToggle: true,
                            allowDepress: false,
                            text: this.txtBtnAdd,
                            tooltip: this.txtBtnAddTooltip,
                            toggleGroup: 'editTools'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSelect',
                            enableToggle: true,
                            allowDepress: false,
                            text: this.txtBtnSelect,
                            tooltip: this.txtBtnSelectTooltip,
                            toggleGroup: 'editTools'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnEdit',
                    tooltip: this.txtBtnEditTooltip,
                    text: this.txtBtnEdit
                },
                {
                    xtype: 'button',
                    itemId: 'btnDelete',
                    tooltip: this.txtBtnDeleteTooltip,
                    text: this.txtBtnDelete
                },
                {
                    xtype: 'fieldset',
                    title: this.txtHelp,
                    itemId: 'fieldsetHelp',
                    items: [
                        {
                            xtype: 'component',
                            itemId: 'helpComponent',
                            id: 'forstfeuerhelp',
                            html: this.txtBasicHelpMessage
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Bewilligung',
                    itemId: 'fieldsetBewilligung',
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            layout: {
                                align: 'stretch',
                                padding: '10 0 10 0',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'geodb_oid',
                                    fieldLabel: 'ID',
                                    labelAlign: 'top',
                                    labelWidth: 25
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'geom',
                                    fieldLabel: 'Koordinate',
                                    labelAlign: 'top',
                                    labelWidth: 75
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'ersteller',
                                    fieldLabel: 'Bearbeiter',
                                    labelAlign: 'top',
                                    labelWidth: 50
                                }
                            ]
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            name: 'dauervon',
                            fieldLabel: 'Von'
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            name: 'dauerbis',
                            fieldLabel: 'Bis'
                        },
                        {
                            xtype: 'radiogroup',
                            fieldLabel: 'Bewilligt',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    name: 'bewilligt',
                                    boxLabel: 'ja',
                                    checked: true,
                                    inputValue: 'true'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'bewilligt',
                                    boxLabel: 'nein',
                                    inputValue: 'false'
                                }
                            ]
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            name: 'grund',
                            fieldLabel: 'Grund'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Bewilligungsnehmer',
                    itemId: 'fieldsetBewilligungsnehmer',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'vorname',
                            fieldLabel: 'Vorname'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'name',
                            fieldLabel: 'Nachname'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'strasse',
                            fieldLabel: 'Adresse'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            name: 'plz',
                            fieldLabel: 'PLZ',
                            selectOnFocus: true,
                            allowDecimals: false,
                            maxValue: 9999,
                            minValue: 1000
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'ort',
                            fieldLabel: 'Ort'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'telefon',
                            fieldLabel: 'Telefon'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'natel',
                            fieldLabel: 'Natel'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    itemId: 'btnSave',
                    text: 'Speichern'
                },
                {
                    xtype: 'button',
                    itemId: 'btnReset',
                    text: 'Zurücksetzen'
                },
                {
                    xtype: 'button',
                    itemId: 'btnCancel',
                    text: 'Abbrechen'
                }
            ]
        });

        me.callParent(arguments);
    }

});